version: '3.8'

networks:
  default:
    driver: bridge
  coolify:
    external: true

services:
  pid-issuer:
    image: ghcr.io/eu-digital-identity-wallet/eudi-srv-pid-issuer:edge
    pull_policy: always
    container_name: pid-issuer
    ports:
      - "9090:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=insecure
      - SPRING_WEBFLUX_BASE_PATH=/pid-issuer
      - SERVER_PORT=8080
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_OPAQUETOKEN_CLIENT_ID=pid-issuer-srv
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_OPAQUETOKEN_CLIENT_SECRET=zIKAV9DIIIaJCzHCVBPlySgU8KgY68U2
      - SERVER_FORWARD_HEADERS_STRATEGY=FRAMEWORK
      - ISSUER_PUBLICURL=https://issuer.authbound.io/pid-issuer
      - ISSUER_AUTHORIZATIONSERVER_PUBLICURL=https://issuer.authbound.io/idp/realms/pid-issuer-realm
      - ISSUER_AUTHORIZATIONSERVER_METADATA=http://keycloak:8080/idp/realms/pid-issuer-realm/.well-known/openid-configuration
      - ISSUER_AUTHORIZATIONSERVER_INTROSPECTION=http://keycloak:8080/idp/realms/pid-issuer-realm/protocol/openid-connect/token/introspect
      - ISSUER_CREDENTIALRESPONSEENCRYPTION_SUPPORTED=true
      - ISSUER_CREDENTIALRESPONSEENCRYPTION_REQUIRED=true
      - ISSUER_CREDENTIALRESPONSEENCRYPTION_ALGORITHMSSUPPORTED=RSA-OAEP-256
      - ISSUER_CREDENTIALRESPONSEENCRYPTION_ENCRYPTIONMETHODS=A128CBC-HS256
      - ISSUER_PID_MSO_MDOC_ENABLED=true
      - ISSUER_PID_MSO_MDOC_ENCODER_DURATION=P30D
      - ISSUER_PID_MSO_MDOC_NOTIFICATIONS_ENABLED=true
      - ISSUER_PID_SD_JWT_VC_ENABLED=true
      - ISSUER_PID_SD_JWT_VC_NOTUSEBEFORE=PT20S
      - ISSUER_PID_SD_JWT_VC_DEFERRED=true
      - ISSUER_PID_SD_JWT_VC_NOTIFICATIONS_ENABLED=true
      - ISSUER_PID_ISSUINGCOUNTRY=GR
      - ISSUER_PID_ISSUINGJURISDICTION=GR-I
      - ISSUER_MDL_ENABLED=true
      - ISSUER_MDL_MSO_MDOC_ENCODER_DURATION=P5D
      - ISSUER_MDL_NOTIFICATIONS_ENABLED=true
      - ISSUER_CREDENTIALOFFER_URI=openid-credential-offer://
      - ISSUER_SIGNING_KEY=GenerateRandom
      - ISSUER_KEYCLOAK_SERVER_URL=http://keycloak:8080/idp
      - ISSUER_KEYCLOAK_AUTHENTICATION_REALM=master
      - ISSUER_KEYCLOAK_CLIENT_ID=admin-cli
      - ISSUER_KEYCLOAK_USERNAME=admin
      - ISSUER_KEYCLOAK_PASSWORD=password
      - ISSUER_KEYCLOAK_USER_REALM=pid-issuer-realm
      - ISSUER_DPOP_PROOF_MAX_AGE=PT1M
      - ISSUER_DPOP_CACHE_PURGE_INTERVAL=PT10M
      - ISSUER_DPOP_REALM=pid-issuer
      - ISSUER_DPOP_NONCE_ENABLED=false
      - ISSUER_CREDENTIALENDPOINT_BATCHISSUANCE_ENABLED=true
      - ISSUER_CREDENTIALENDPOINT_BATCHISSUANCE_BATCHSIZE=10
      - ISSUER_CNONCE_EXPIRATION=PT5M
    networks:
      - default
      - coolify
    healthcheck:
      test: ["CMD", "curl", "-f", "http://issuer.authbound.io/pid-issuer/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
        - caddy.enable=true
        - caddy=issuer.authbound.io
        - caddy.handle=/pid-issuer/*
        - caddy.handle.reverse_proxy=pid-issuer:8080
        - caddy.handle.reverse_proxy.health_path=/pid-issuer/actuator/health
        - caddy.handle.reverse_proxy.health_interval=30s
        - caddy.handle=/.well-known/jwt-vc-issuer/pid-issuer
        - caddy.handle.respond={"issuer":"https://issuer.authbound.io/pid-issuer","jwks_uri":"https://issuer.authbound.io/pid-issuer/public_keys.jwks"}
        - caddy.handle.respond.status=200