version: '3.8'

networks:
  default:
    driver: bridge
  coolify:
    external: true

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.5-0
    container_name: keycloak
    command:
      - start-dev
      - --import-realm
      - --features=dpop
    environment:
      - KC_PROXY_HEADERS=xforwarded
      - KC_HTTP_ENABLED=true
      - KC_HTTP_RELATIVE_PATH=/idp
      - KC_HOSTNAME=https://pid-issuer.authbound.io/idp
      - KC_HOSTNAME_BACKCHANNEL_DYNAMIC=true
      - KC_HTTPS_CERTIFICATE_FILE=/etc/ssl/certs/keycloak.tls.crt
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/etc/ssl/certs/keycloak.tls.key
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=password
    healthcheck:
      test: "bash /opt/keycloak/health-check.sh"
      interval: 5s
      timeout: 10s
      retries: 12
      start_interval: 30s
    volumes:
      - ./keycloak/extra/health-check.sh:/opt/keycloak/health-check.sh
      - ./keycloak/realms/:/opt/keycloak/data/import
      - ./keycloak/certs/:/etc/ssl/certs/
    networks:
      - default
      - coolify
    labels:
      # Caddy Docker Proxy labels for routing
      - caddy.enable=true
      - caddy=pid-issuer.authbound.io
      - caddy.handle=/idp/*
      - caddy.handle.reverse_proxy=keycloak:8080
      - caddy.handle.reverse_proxy.health_path=/health
      - caddy.handle.reverse_proxy.health_interval=30s

  pid-issuer:
    image: ghcr.io/eu-digital-identity-wallet/eudi-srv-pid-issuer:edge
    pull_policy: always
    container_name: pid-issuer
    depends_on:
      keycloak:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=insecure
      - SPRING_WEBFLUX_BASE_PATH=/pid-issuer
      - SERVER_PORT=8080
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_OPAQUETOKEN_CLIENT_ID=pid-issuer-srv
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_OPAQUETOKEN_CLIENT_SECRET=zIKAV9DIIIaJCzHCVBPlySgU8KgY68U2
      - SERVER_FORWARD_HEADERS_STRATEGY=FRAMEWORK
      - ISSUER_PUBLICURL=https://pid-issuer.authbound.io/pid-issuer
      - ISSUER_AUTHORIZATIONSERVER_PUBLICURL=https://pid-issuer.authbound.io/idp/realms/pid-issuer-realm
      - ISSUER_AUTHORIZATIONSERVER_METADATA=https://keycloak:8443/idp/realms/pid-issuer-realm/.well-known/openid-configuration
      - ISSUER_AUTHORIZATIONSERVER_INTROSPECTION=https://keycloak:8443/idp/realms/pid-issuer-realm/protocol/openid-connect/token/introspect
      - ISSUER_CREDENTIALRESPONSEENCRYPTION_SUPPORTED=true
      - ISSUER_CREDENTIALRESPONSEENCRYPTION_REQUIRED=true
      - ISSUER_CREDENTIALRESPONSEENCRYPTION_ALGORITHMSSUPPORTED=RSA-OAEP-256
      - ISSUER_CREDENTIALRESPONSEENCRYPTION_ENCRYPTIONMETHODS=A128CBC-HS256
      - ISSUER_PID_MSO_MDOC_ENABLED=true
      - ISSUER_PID_MSO_MDOC_ENCODER_DURATION=P30D
      - ISSUER_PID_MSO_MDOC_NOTIFICATIONS_ENABLED=true
      - ISSUER_PID_SD_JWT_VC_ENABLED=true
      - ISSUER_PID_SD_JWT_VC_NOTUSEBEFORE=PT20S
      - ISSUER_PID_SD_JWT_VC_DEFERRED=true
      - ISSUER_PID_SD_JWT_VC_NOTIFICATIONS_ENABLED=true
      - ISSUER_PID_ISSUINGCOUNTRY=GR
      - ISSUER_PID_ISSUINGJURISDICTION=GR-I
      - ISSUER_MDL_ENABLED=true
      - ISSUER_MDL_MSO_MDOC_ENCODER_DURATION=P5D
      - ISSUER_MDL_NOTIFICATIONS_ENABLED=true
      - ISSUER_CREDENTIALOFFER_URI=openid-credential-offer://
      - ISSUER_SIGNING_KEY=GenerateRandom
      - ISSUER_KEYCLOAK_SERVER_URL=https://keycloak:8443/idp
      - ISSUER_KEYCLOAK_AUTHENTICATION_REALM=master
      - ISSUER_KEYCLOAK_CLIENT_ID=admin-cli
      - ISSUER_KEYCLOAK_USERNAME=admin
      - ISSUER_KEYCLOAK_PASSWORD=password
      - ISSUER_KEYCLOAK_USER_REALM=pid-issuer-realm
      - ISSUER_DPOP_PROOF_MAX_AGE=PT1M
      - ISSUER_DPOP_CACHE_PURGE_INTERVAL=PT10M
      - ISSUER_DPOP_REALM=pid-issuer
      - ISSUER_DPOP_NONCE_ENABLED=false
      - ISSUER_CREDENTIALENDPOINT_BATCHISSUANCE_ENABLED=true
      - ISSUER_CREDENTIALENDPOINT_BATCHISSUANCE_BATCHSIZE=10
      - ISSUER_CNONCE_EXPIRATION=PT5M
    networks:
      - default
      - coolify
    labels:
      # Caddy Docker Proxy labels for routing
      - caddy.enable=true
      - caddy=pid-issuer.authbound.io
      - caddy.handle=/pid-issuer/*
      - caddy.handle.reverse_proxy=pid-issuer:8080
      - caddy.handle.reverse_proxy.health_path=/actuator/health
      - caddy.handle.reverse_proxy.health_interval=30s
      # Metadata endpoint
      - caddy.handle=/.well-known/jwt-vc-issuer/pid-issuer
      - caddy.handle.respond={"issuer":"https://pid-issuer.authbound.io/pid-issuer","jwks_uri":"https://pid-issuer.authbound.io/pid-issuer/public_keys.jwks"}
